---
title: "EDAV on CitiBike"
author: "Lehui Liu"
date: "2018/11/18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
Explain why you chose this topic, and the questions you are interested in studying.
List team members and a description of how each contributed to the project.

## Description of data
Describe how the data was collected, how you accessed it, and any other noteworthy features.

## Analysis of data quality
Provide a detailed, well-organized description of data quality, including textual description, graphs, and code.

## Main analysis (Exploratory Data Analysis)
Provide a detailed, well-organized description of your findings, including textual description, graphs, and code. Your focus should be on both the results and the process. Include, as reasonable and relevant, approaches that didn’t work, challenges, the data cleaning process, etc.

## Executive summary (Presentation-style)
Provide a short nontechnical summary of the most revealing findings of your analysis written for a nontechnical audience. The length should be approximately two pages (if we were using pages…) Take extra care to clean up your graphs, ensuring that best practices for presentation are followed.

## Interactive component
Select one (or more) of your key findings to present in an interactive format. Be selective in the choices that you present to the user; the idea is that in 5-10 minutes, users should have a good sense of the question(s) that you are interested in and the trends you’ve identified in the data. In other words, they should understand the value of the analysis, be it business value, scientific value, general knowledge, etc.
Interactive graphs must follow all of the best practices as with static graphs in terms of perception, labeling, accuracy, etc.

You may choose the tool (D3, Shiny, or other) The complexity of your tool will be taken into account: we expect more complexity from a higher-level tool like Shiny than a lower-level tool like D3, which requires you to build a lot from scratch.

Make sure that the user is clear on what the tool does and how to use it.

Publish your graph somewhere on the web and provide a link in your report in the interactive section. The obvious choices are blockbuilder.org to create a block for D3, and shinyapps.io for Shiny apps but other options are fine. You are encouraged to share experiences on Piazza to help classmates with the publishing process.

As applicable, all of the following will be considered in the grading process:

Choice of data and plot types to present
Clear relevance to question(s), project in general
Design of interactive component(s)
Clarity of presentation, including instructions
Technical execution (include a description of what you would work on in the future, what you’ve attempted, etc. so we know it’s on your radar)

## Conclusion
Discuss limitations and future directions, lessons learned.
